### ISSUE TITLE
RbConfig::CONFIG['LIBS'] doesn't include jemalloc on Heroku cedar-14 stack

### ISSUE THREAD

**Issue by frederikspang** [mojodna/heroku-buildpack-jemalloc#9]
I'm trying to use the buildpack with pgbouncer-stunnel, and I cant seem to make jemalloc.sh work correctly in my Procfile, nor in the console.

Adding `puts RbConfig::CONFIG['LIBS']` in config.ru prints out `-lpthread -ldl -lcrypt -lm`, and so does running `jemalloc.sh bundle exec rails c` and running the command.

**Buildpacks:**
1. https://github.com/mojodna/heroku-buildpack-jemalloc.git
2. heroku/ruby
3. https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks
4. https://github.com/heroku/heroku-buildpack-pgbouncer

`jemalloc.sh echo $LD_PRELOAD` returns nothing, and even if I do an `export LD_PRELOAD='...'` with the correct path (ensured by `cat $LD_PRELOAD`), nothing works.

Am I missing some vital step to actually install jemalloc, like I've done locally with Homebrew?

UPDATE: Doesn't work with 3.6.0 either.
UPDATE2: Running newest buildpack (4), on Heroku-16 adds `-lgmp` to the Libs. Still no jemalloc

**Comment by frodsan** [comment]
Tested on heroku-16:

```
$ cat Procfile
web: jemalloc.sh bin/puma -C config/puma.rb
worker: jemalloc.sh bin/sidekiq -C config/sidekiq.yml
$ heroku buildpacks
1. https://github.com/mojodna/heroku-buildpack-jemalloc.git
2. heroku/ruby
$ heroku run bash
$ jemalloc.sh ruby -r rbconfig -e "puts RbConfig::CONFIG['LIBS']"
-lpthread -lgmp -ldl -lcrypt -lm
```

**Comment by nateberkopec** [comment]
RbConfig::CONFIG['LIBS'] is set by the configure script at compile time. Dynamically loading a library with LD_PRELOAD will not change it.

**Comment by nateberkopec** [comment]
I'm not sure what a good way to confirm jemalloc was actually loaded would be. We can't access /proc/pid/maps on Heroku.
